project_name: relayer
env:
  - CGO_ENABLED=1
builds:
  - id: darwin-amd64
    main: ./main.go
    binary: rly
    hooks:
      pre:
        - wget https://github.com/CosmWasm/wasmvm/releases/download/{{ .Env.LIBWASM_VERSION }}/libwasmvmstatic_darwin.a -O /lib/libwasmvmstatic_darwin.a
    goos:
      - darwin
    goarch:
      - amd64
    env:
      - CC=o64-clang
      - CGO_LDFLAGS=-L/lib
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -s -w -X github.com/icon-project/relayer/v2/cmd.Version={{ .Tag }}
      - -linkmode=external
    tags:
      - static_wasm
  - id: darwin-arm64
    main: ./main.go
    binary: rly
    hooks:
      pre:
        - wget https://github.com/CosmWasm/wasmvm/releases/download/{{ .Env.LIBWASM_VERSION }}/libwasmvmstatic_darwin.a -O /lib/libwasmvmstatic_darwin.a
    goos:
      - darwin
    goarch:
      - arm64
    env:
      - CC=oa64-clang
      - CGO_LDFLAGS=-L/lib
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -s -w -X github.com/icon-project/relayer/v2/cmd.Version={{ .Tag }}
      - -linkmode=external
    tags:
      - static_wasm
  - id: linux-amd64
    main: ./main.go
    binary: rly
    hooks:
      pre:
        - wget https://github.com/CosmWasm/wasmvm/releases/download/{{ .Env.LIBWASM_VERSION }}/libwasmvm_muslc.x86_64.a -O /usr/lib/x86_64-linux-gnu/libwasmvm_muslc.a
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CC=x86_64-linux-gnu-gcc
      - CXX=x86_64-linux-gnu-g++
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -s -w -X github.com/icon-project/relayer/v2/cmd.Version={{ .Tag }}
      - -linkmode=external
      - -extldflags '-Wl,-z,muldefs -lm'
    tags:
      - muslc
      - netgo
  - id: linux-arm64
    main: ./main.go
    binary: rly
    hooks:
      pre:
        - wget https://github.com/CosmWasm/wasmvm/releases/download/{{ .Env.LIBWASM_VERSION }}/libwasmvm_muslc.aarch64.a -O /usr/lib/aarch64-linux-gnu/libwasmvm_muslc.a
    goos:
      - linux
    goarch:
      - arm64
    env:
      - CC=aarch64-linux-gnu-gcc
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -s -w -X github.com/icon-project/relayer/v2/cmd.Version={{ .Tag }}
      - -linkmode=external
      - -extldflags "-static"
    tags:
      - muslc
      - netgo

archives:
  - id: golang-cross
    builds:
      - darwin-amd64
      - darwin-arm64
      - linux-amd64
      - linux-arm64
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz
    wrap_in_directory: true

checksum:
  name_template: SHA256SUMS-{{.Version}}.txt
  algorithm: sha256

release:
  prerelease: auto
  draft: false