name: Bump version
on:
  push:
    branches:
      - main
      - prerelease
      - release.*
jobs:
  update-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: false
          pre_release_branches: prerelease
          release_branches: release.*
          append_to_pre_release_tag: alpha
          tag_prefix: v
